-- Run this after login-page update (existing database)
USE nexpos;

-- Default password for all seeded users: admin123
-- bcrypt hash generated by bcryptjs:
-- $2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G

INSERT INTO employees (id, name, email, role, password_hash, sales_count, total_sales)
VALUES
  ('john', 'John Admin', 'john@pos.com', 'Admin', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 150, 12500.00),
  ('sarah', 'Sarah Manager', 'sarah@pos.com', 'Manager', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 200, 18000.00),
  ('mike', 'Mike Cashier', 'mike@pos.com', 'Cashier', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 300, 9500.00)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  email = VALUES(email),
  role = VALUES(role),
  password_hash = VALUES(password_hash),
  sales_count = VALUES(sales_count),
  total_sales = VALUES(total_sales);

SELECT id, name, email, role FROM employees WHERE email IN ('john@pos.com', 'sarah@pos.com', 'mike@pos.com');
-- Run this after login-page update (existing database)
USE nexpos;

-- Default password for all seeded users: admin123
-- bcrypt hash generated by bcryptjs:
-- $2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G

INSERT INTO employees (id, name, email, role, password_hash, sales_count, total_sales)
VALUES
  ('john', 'John Admin', 'john@pos.com', 'Admin', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 150, 12500.00),
  ('sarah', 'Sarah Manager', 'sarah@pos.com', 'Manager', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 200, 18000.00),
  ('mike', 'Mike Cashier', 'mike@pos.com', 'Cashier', '$2b$10$7VqJ3uNuNRzygrz81YCAzuINsL3qwkdciRF.bs5hZ5zPBNH4OQO.G', 300, 9500.00)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  email = VALUES(email),
  role = VALUES(role),
  password_hash = VALUES(password_hash),
  sales_count = VALUES(sales_count),
  total_sales = VALUES(total_sales);

SELECT id, name, email, role FROM employees WHERE email IN ('john@pos.com', 'sarah@pos.com', 'mike@pos.com');

